### ISSUE TITLE
Use javascipt prototype

### ISSUE THREAD

**Issue by ryuran** [AcceDe-Web/tablist#3]
Why do not use `Tablist.prototype` for define member function?

For example:
`Tablist.prototype.firstActiveTab = function firstActiveTab() {…}`

**Comment by enwin** [comment]
This is just how we’re used to code our JavaScript. We got the habit of it and didn’t think of changing our coding style for this plugin.

**Comment by ryuran** [comment]
Every common functions to each object should be a member on prototype.
Because:
- if it's directly a member off the Tablist object function is on memory for each Tablist.
- a specific TabList object can override a function of his prototype

You can play with it : https://jsfiddle.net/6uj650e2/

**Comment by borisschapira** [comment]
Prototype-oriented programmation is not a code style.

**Comment by enwin** [comment]
Thanks for your input. Prototype-oriented programming is one side of object creation, this & bind is another way to achieve the same goal (creating an object). Yes, it means that every instance will load the methods but web browsers are intelligent enough to optimize the duplicated methods.

As for overriding methods, the user can override the exposed methods. We don't want the core methods to be overridden as it could prevent the library to work as expected accessibility-wise.

We choose this notation for our scripts but remember, when it comes to object creation there's
![no "right" way](https://cloud.githubusercontent.com/assets/1038339/19146722/0d60a6ae-8bb5-11e6-99e1-749f1241dd2d.png)

😄

**Comment by hmalaud** [comment]
I'd be curious to see a Prototyped way though, maybe you guys @borisschapira and @ryuran can fork the project and transpose it?

**Comment by ryuran** [comment]
You can as well use `this` and `bind` if you use prototype.
