### ISSUE TITLE
First letter of an input in a tab does not appear

### ISSUE THREAD

**Issue by KriKroff** [AcceDe-Web/tablist#4]
Hi,

My team have recently used your component to handle tabs.
There is a bad behavior when a tab containing a text input is displayed and the user click directly on it.
The first letter typed is ignored.

Here is an example : https://jsfiddle.net/57gxbe56/
Click directly on the input, then try to type "abc" only "bc" appears.

This wrong behavior comes from handlePanel calling HandlePanelFocus if no tab is selected.
HandlePanelFocus does a preventDefault on the keyBoardEvent.

**Comment by enwin** [comment]
Hello,

Thanks for your feedback, we're gonna have a look into it

**Comment by enwin** [comment]
Merged in `master` and updated on npm!

Hope you'll like it
